export const tabHeader = {
    delvTabHead: {
        name: "发货单名称",
        entityNo: "发货单单号",
        amount: "发货单总金额",
        seller: "卖方名称",
        buyer: "买方名称",
        recvgStatusFlag: "收货状态",
        drDate: "发货日期"
    },
    recvTabHead: {
        // name: "收货单名称",
        entityNo: "收货单单号",
        buyer: "买方名称",
        seller: "卖方名称",
        createTime: '创建日期',
        drDate: "收货日期",
        // operator: "出货单操作人",
        amount: "收货单总金额",
        // myRoleType: "我方角色",
        // unloadAddress: "下货地址",
        // sellerAddress: "买家地址",
        // buyerAddress: "卖家地址",
        // buyerTel: "买家电话",
        // sellerTel: "卖家电话",
    },
    contractTabHead: {
        name: "合同名称",
        entityNo: "合同编号",
        contractContent: "合同内容",
        businessType: "业务类型",
        cType: "合同类型",
        buyer: "买方",
        seller: "卖方",
        // currency: "币种",
        amount: "合同金额(元)",
        signingDate: "合同签署时间",
        startDate: "合同生效日期",
        endDate: "合同到期日期"
    },
    orderTabHead: {
        name: "订单名称",
        entityNo: "订单单号",
        // deliveryType: "发货类型",
        amount: "订单金额",
        buyer: "买方名称",
        seller: "卖方名称",
        // orderAddress: "订单地址",
        // unloadAddress: "下货地址",
        createTime: "订单创建日期",
        // clientName: "客户名称",
        startDate: "订单发起日期",
        // endDate: "订单结束日期",
        // inputDate: "订单录入日期",
        // remarks: "备注",
        goodsHead:{
            title: "商品信息",
            children: {
                skuId: "货品编号",
                goodsName: "货品名称",
                remarks: "货品描述",
                spec: "商品规格",
                quantity: "数量",
                unit: "单位",
                manufacturer: "制造商",
                unitPrice: "单价",
                taxRate: "税率(%)",
                // totalAmount: "合计(元)"
            }
        }
    },
    settlementTabHead: {
        entityNo: "结算单单号",
        name: "结算单名称",
        buyer: "买方",
        seller: "卖方",
        settlePrice: "结算单价",
        // type: "类型",
        totalAmount: "结算单总金额",
        paidAmount: "结算单支付金额",
        balanceAmount: "余额",
        settleDate: "结算日期",
        // createTime: "上传日期",
        startDate: "结算开始日期",
        endDate: "结算结束日期",
        // settleCompany: "结算单位",
    }
}