export const dataDetailForm = {
    TRADECONTRACT: {
        name: "合同名称",
        entityNo: "合同编号",
        contractContent: "合同内容",
        buzType: "业务类型",
        type: "合同类型",
        buyer: "买方",
        seller: "卖方",
    },
    TRADECONTRACTDetail: {
        name: "合同名称",
        entityNo: "合同编号",
        contractContent: "合同内容",
        buzType: "业务类型",
        type: "合同类型",
        buyer: "买方",
        seller: "卖方",
        currency: "币种",
        amount: "合同金额(元)",
        signingDate: "合同签署时间",
        startDate: "合同生效日期",
        endDate: "合同到期日期"
    },
    TRADEINVOICE: {
        fpdm: "发票代码",
        fphm: "发票号码",
        kprq: "开票日期",
        code: "发票校验码",
        num: "发票机器码",
        taxamount: "税额合计",
        goodsamount: "价格合计",
        sumamount: "价税合计"
    },
    TRADEINVOICEDetail: {
        fpdm: "发票代码",
        fphm: "发票号码",
        code: "发票校验码",
        kprq: "开票日期",
        num: "发票机器码",
        taxamount: "税额合计",
        goodsamount: "价格合计",
        sumamount: "价税合计",
        quantityAmount: "数量合计",
        checkStatus: "状态",
        updateTime: "更新时间"
    },
    TRADEORDER: {
        name: "订单名称",
        entityNo: "订单单号",
        deliveryType: "发货类型",
        amount: "订单金额",
        buyer: "买方名称",
        seller: "卖方名称"
    },
    TRADEORDERDetail: {
        name: "订单名称",
        entityNo: "订单单号",
        deliveryType: "发货类型",
        amount: "订单金额",
        buyer: "买方名称",
        seller: "卖方名称",
        orderAddress: "订单地址",
        unloadAddress: "下货地址",
        createTime: "订单发起日期",
        clientName: "客户名称",
        startDate: "订单发起日期",
        endDate: "订单结束日期",
        inputDate: "订单录入日期",
        remarks: "备注"
    },
    TRADEDLVRGOODS: {
        name: "发货单名称",
        entityNo: "发货单单号",
        amount: "发货单总金额",
        seller: "卖方名称",
        buyer: "买方名称",
        operator: "出货单操作人"
    },
    TRADEDLVRGOODSDetail: {
        name: "发货单名称",
        entityNo: "发货单单号",
        amount: "发货单总金额",
        seller: "卖方名称",
        buyer: "买方名称",
        operator: "出货单操作人",
        recvgStatusFlag: "收货状态",
        unloadAddress: "下货地址",
        sellerAddress: "买家地址",
        buyerAddress: "卖家地址",
        buyerTel: "买家电话",
        sellerTel: "卖家电话",
        drDate: "发货日期"
    },
    TRADERECVGGOODS: {
        name: "收货单名称",
        entityNo: "收货单单号",
        buyer: "买方名称",
        seller: "卖方名称",
        drDate: "收货日期",
        operator: "出货单操作人"
    },
    TRADERECVGGOODSDetail: {
        name: "收货单名称",
        entityNo: "收货单单号",
        buyer: "买方名称",
        seller: "卖方名称",
        drDate: "收货日期",
        operator: "出货单操作人",
        amount: "收货单总金额",
        myRoleType: "我方角色",
        unloadAddress: "下货地址",
        sellerAddress: "买家地址",
        buyerAddress: "卖家地址",
        buyerTel: "买家电话",
        sellerTel: "卖家电话"
    },
    TRADEPRESETTLEMENT: {
        settlementNo: "单次结算单单号",
        name: "单次结算单名称",
        settlePrice: "结算单价",
        paidAmount: "结算单支付金额",
        balanceAmount: "余额",
        settleDate: "结算日期",
        settlePrice: "结算单价",
    },
    TRADEPRESETTLEMENTDetail: {
        settlementNo: "单次结算单单号",
        name: "单次结算单名称",
        settlePrice: "结算单价",
        paidAmount: "结算单支付金额",
        balanceAmount: "余额",
        // type: "类型",
        settleCompany: "结算单位",
        startDate: "结算开始日期",
        endDate: "结算结束日期",
        settleDate: "结算日期",
        buyer: "买方",
        seller: "卖方",
    },
    TRADESETTLEMENT: {
        entityNo: "结算单单号",
        name: "结算单名称",
        totalAmount: "结算单总金额",
        buyer: "买方",
        seller: "卖方",
        settleDate: "结算日期",
        settlePrice: "结算单价",
    },
    TRADESETTLEMENTDetail: {
        entityNo: "结算单单号",
        name: "结算单名称",
        totalAmount: "结算单总金额",
        buyer: "买方",
        seller: "卖方",
        settleDate: "结算日期",
        settlePrice: "结算单价",
        // type: "类型",
      paidAmount: "结算单支付金额",
      balanceAmount: "余额",
        startDate: "结算开始日期",
        endDate: "结算结束日期",
        settleCompany: "结算单位",
    },
    TRADECHECKAPPLY: {
        checkApplyNo: "报检单单号",
        name: "报检单名称",
        quantity: "报检数量",
        applyDept: "报检部门",
        supplier: "供应商",
        applyDate: "报检日期",
    },
    TRADECHECKAPPLYDetail: {
        checkApplyNo: "报检单单号",
        name: "报检单名称",
        quantity: "报检数量",
        applyDept: "报检部门",
        supplier: "供应商",
        applyDate: "报检日期",
        belongGroup: "所属集团",
        sampleWay: "取样方式",
        review: "复检",
        type: "报检类型",
        rejectReason: "拒收原因",
        details: "报检详情",
        unit: "单位",
        remarks: "备注",
    },
    TRADEDQUALITY: {
        entityNo: "质检单编号",
        name: "质检单名称",
        institute: "质检机构",
        buyer: "买方",
        seller: "卖方",
        inspectionBatch: "质检批次",
        qualityDate: "质检日期",
    },
    TRADEDQUALITYDetail: {
        entityNo: "质检单编号",
        name: "质检单名称",
        institute: "质检机构",
        buyer: "买方",
        seller: "卖方",
        startDate: "质检开始日期",
        endDate: "质检结束日期",
        qualityGrade: "质量等级",
        inspectionItem: "核验项目",
        checkApplyNumber: "报检数量：",
        inspectionNumber: "核验数量",
        reachNumber: "合格数量",
        reachRate: "合格率",
        inspectionBatch: "核验批次",
        type: "类型",
        remarks: "备注",
    },
    TRADEDPONDERATION: {
        name: "过磅单名称",
        entityNo: "过磅单单号",
        carPlateNumber: "车牌号",
        driver: "驾驶员",
        roughWeight: "毛重",
        suttleWeight: "净重",
    },
    TRADEDPONDERATIONDetail: {
        name: "过磅单名称",
        entityNo: "过磅单单号",
        carPlateNumber: "车牌号",
        driver: "驾驶员",
        roughWeight: "毛重",
        tareWeight: "皮重",
        suttleWeight: "净重",
        measureUnit: "计量单位",
        measureWay: "计量方式",
        type: "类型",
        buyer: "买方名称",
        seller: "卖方名称",
        netWeight: "总净重",
        startDate: "货品明细中过磅最早日期",
        endDate: "货品明细中过磅最晚日期",
        weighingDate: "过磅时间",
        remarks: "备注",
    },
    TRADELOGISTICS: {
        logisticsNo: "物流单号",
        name: "物流名称",
        carCode: "车牌号",
        driver: "司机",
        mobile: "手机号",
        idCard: "身份证号",
        quantity: "数量",
        tyBill: "承运单号",
    },
    TRADELOGISTICSDetail: {
        logisticsNo: "物流单号",
        name: "物流名称",
        carCode: "车牌号",
        driver: "司机",
        mobile: "手机号",
        idCard: "身份证号",
        quantity: "数量",
        unit: "单位",
        tyBill: "承运单号",
        isused: "状态", //8 作废 , 0未处理，1 LE已同步，2 已验证取卡，3已进厂，9 已二次过磅，10已出厂
        resourceType: "", //来源，0为销售出货，1为采购送货
        remarks: "备注",
        createTime: "创建日期",
        lastUpdateTime: "更新日期"
    }
}
